spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letsgo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      pool-name: HikariThreadPool
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:com/letsgo/mapper/xml/*Mapper.xml
  type-aliases-package: com.letsgo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: assign_id #全局唯一ID

logging:
  level:
    com.study.miaosha.mapper: debug
